[package]
name = "target-spec"
version = "0.4.1"
description = "Evaluate Cargo.toml target specifications"
documentation = "https://docs.rs/target-spec"
repository = "https://github.com/facebookincubator/cargo-guppy"
authors = ["Jack Moffitt <metajack@fb.com>", "Rain <rain1@calibra.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cargo", "targets", "platforms", "os", "cpu"]
categories = ["development-tools", "parser-implementations"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges]
circle-ci = { repository = "facebookincubator/cargo-guppy", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
cfg-expr = "0.4.1"
proptest = { version = "0.10.1", optional = true }
serde = { version = "1.0.116", optional = true, features = ["derive"] }

[dev-dependencies]
toml = "0.5.7"

[features]
proptest010 = ["proptest"]
summaries = ["serde"]
