[package]
name = "target-spec"
version = "0.2.3"
description = "Evaluate Cargo.toml target specifications"
documentation = "https://docs.rs/target-spec"
repository = "https://github.com/facebookincubator/cargo-guppy"
authors = ["Jack Moffitt <metajack@fb.com>", "Rain <rain1@calibra.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cargo", "targets", "platforms", "os", "cpu"]
categories = ["development-tools", "parser-implementations"]
edition = "2018"

[badges]
circle-ci = { repository = "facebookincubator/cargo-guppy", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
cfg-expr = "0.3.0"
once_cell = "1.3.1"
