[package]
name = "cargo-compare"
version = "0.1.0"
authors = ["Rain <rain1@fb.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
# TODO: update to cargo 0.52.0 when it comes out
cargo = { git = "https://github.com/rust-lang/cargo.git", branch = "rust-1.51.0" }
diffus = "0.9.1"
either = "1.6.1"
itertools = "0.10.0"
guppy = { path = "../../guppy" }
guppy-cmdlib = { path = "../../guppy-cmdlib", features = ["proptest1"] }
structopt = "0.3.21"
tempfile = "3.2.0"
once_cell = "1.7.0"
proptest = "1.0.0"
