[package]
name = "cargo-compare"
version = "0.1.0"
authors = ["Rain <rain1@fb.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
cargo = "0.50.0"
diffus = "0.9.1"
either = "1.6.1"
itertools = "0.10.0"
guppy = { path = "../../guppy" }
guppy-cmdlib = { path = "../../guppy-cmdlib", features = ["proptest010"] }
structopt = "0.3.21"
tempfile = "3.2.0"
once_cell = "1.5.2"
proptest = "0.10.1"
