[workspace]
members = [
    "cargo-guppy",
    "fixtures",
    "guppy",
    "guppy-cmdlib",
    "guppy-summaries",
    "target-spec",
    "tools/benchmarks",
    "tools/cargo-compare",
    "tools/fixture-manager",
]
