[package]
name = "cargo-guppy"
version = "0.1.0"
authors = ["Rain <rain1@calibra.com>", "Brandon Williams <bmwill@calibra.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-guppy-lib = { version = "0.1.0", path = "../cargo-guppy-lib" }
serde_json = "1.0.40"
structopt = "0.3.0"
