[package]
name = "cargo-guppy"
version = "0.1.0"
authors = ["Rain <rain1@calibra.com>", "Brandon Williams <bmwill@calibra.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0.33"
clap = "2.33.3"
dialoguer = "0.7.0"
guppy = { version = "^0.5.0-rc.1", path = "../guppy", features = ["summaries"] }
guppy-cmdlib = { path = "../guppy-cmdlib" }
itertools = "0.9.0"
pathdiff = "0.2.0"
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.59"
structopt = "0.3.19"
toml_edit = "0.2.0"
