[package]
name = "cargo-guppy"
version = "0.1.0"
authors = ["Rain <rain1@calibra.com>", "Brandon Williams <bmwill@calibra.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0.25"
clap = "2.33"
dialoguer = "0.6.2"
guppy = { version = "^0.5.0-rc.1", path = "../guppy", features = ["summaries"] }
guppy-cmdlib = { path = "../guppy-cmdlib" }
itertools = "0.9.0"
pathdiff = "0.2.0"
serde = { version = "1.0.40", features = ["derive"] }
serde_json = "1.0.51"
structopt = "0.3.0"
# Includes the changes in https://github.com/ordian/toml_edit/pull/88.
toml_edit = { git = "https://github.com/sunshowers/toml_edit.git", rev = "296e1cd8f9c3a62c7df7c3b4123d3ef81424fcd9" }
