[package]
name = "cargo-guppy"
version = "0.1.0"
authors = ["Rain <rain1@calibra.com>", "Brandon Williams <bmwill@calibra.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0.25"
clap = "2.33"
guppy = { version = "0.4.0", path = "../guppy", features = ["summaries"] }
guppy-cmdlib = { path = "../guppy-cmdlib" }
itertools = "0.9.0"
serde = { version = "1.0.40", features = ["derive"] }
serde_json = "1.0.51"
structopt = "0.3.0"
