[package]
name = "cargo-guppy"
version = "0.1.0"
authors = ["Rain <rain1@calibra.com>", "Brandon Williams <bmwill@calibra.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1.0.25"
clap = "2.33"
guppy = { version = "0.1.0", path = "../guppy" }
itertools = "0.8.2"
semver = "0.9.0"
serde = "1.0.40"
serde_json = "1.0.40"
structopt = "0.3.0"
target-spec = { git = "https://github.com/metajack/target-spec" }
