version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:stretch
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Rust Components
          command: |
            rustup component add rustfmt
      - run:
          name: Setup Env
          command: |
            echo 'export RUSTFLAGS="-D warnings"' >> $BASH_ENV
      - run:
          name: Linting
          command: |
            cargo fmt -- --check
      - run:
          name: Build and Test
          command: |
            cargo build
            cargo test
