[package]
name = "guppy-summaries"
version = "0.3.2"
description = "Build summaries for Cargo, created by guppy."
documentation = "https://docs.rs/guppy-summaries"
repository = "https://github.com/facebookincubator/cargo-guppy"
authors = ["Rain <rain1@fb.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cargo", "dependencies", "guppy", "summaries"]
categories = ["config", "data-structures", "development-tools", "parser-implementations"]
edition = "2018"
exclude = [
    # Readme template that doesn't need to be included.
    "README.tpl",
]

[dependencies]
camino = { version = "1.0.0", features = ["serde1"] }
cfg-if = "1.0.0"
diffus = "0.9.1"
toml = "0.5.8"
semver = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0.123", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
serde_json = "1.0"
