[package]
name = "guppy-summaries"
version = "0.2.0"
description = "Build summaries for Cargo, created by guppy."
documentation = "https://docs.rs/guppy-summaries"
repository = "https://github.com/facebookincubator/cargo-guppy"
authors = ["Rain <rain1@calibra.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cargo", "dependencies", "guppy", "summaries"]
categories = ["config", "data-structures", "development-tools", "parser-implementations"]
edition = "2018"
exclude = [
    # Readme template that doesn't need to be included.
    "README.tpl",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diffus = "0.9.1"
toml = "0.5.7"
semver = { version = "0.10.0", features = ["serde"] }
serde = { version = "1.0.116", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "0.6.1"
