[package]
name = "determinator"
version = "0.1.0"
authors = ["Rain <rain1@fb.com>"]
edition = "2018"
repository = "https://github.com/facebookincubator/cargo-guppy"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = [
    "cargo",
    "guppy",
    "determinator",
    "package-changes",
    "build-caching",
]
categories = [
    "config",
    "development-tools",
]
include = [
    "README.md",
    "**/*.rs",
    # Include default rules with the package.
    "default-rules.toml",
]
exclude = [
    # Readme template that doesn't need to be included.
    "README.tpl",
]

[dependencies]
globset = "0.4.6"
guppy = { version = "0.6.0", path = "../../guppy", features = ["rayon1", "summaries"] }
itertools = "0.9"
once_cell = "1.5.2"
petgraph = { version = "0.5", default-features = false, features = ["graphmap"] }
rayon = "1.5.0"
serde = { version = "1", features = ["derive"] }
toml = "0.5"

[dev-dependencies]
fixtures = { path = "../../fixtures" }
