[package]
name = "hakari"
version = "0.1.0"
description = "Manage workspace-hack packages that do feature unification inside workspaces."
authors = ["Rain <rain1@fb.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = [
    "cargo",
    "dependencies",
    "workspace-hack",
    "feature-unification",
    "guppy",
]
categories = [
    "development-tools",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
atomicwrites = "0.2.5"
cfg-if = "1.0.0"
diffy = "0.2.1"
guppy = { version = "0.6.2", path = "../../guppy", features = ["rayon1"] }
pathdiff = "0.2.0"
proptest = { version = "0.10", optional = true }
proptest-derive = { version = "0.2.0", optional = true }
rayon = "1.5.0"
serde = { version = "1.0.123", features = ["derive"], optional = true }
toml = { version = "0.5.8", optional = true }
twox-hash = { version = "1.6.0", default-features = false }

[dev-dependencies]
fixtures = { path = "../../fixtures" }

[features]
proptest010 = ["proptest", "proptest-derive", "guppy/proptest010"]
summaries = ["guppy/summaries", "serde", "toml"]
