[package]
name = "guppy"
version = "0.1.1"
description = "Track and query Cargo dependency graphs."
documentation = "https://docs.rs/guppy"
repository = "https://github.com/calibra/cargo-guppy"
authors = ["Rain <rain1@calibra.com>", "Brandon Williams <bmwill@calibra.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cargo", "dependencies", "reverse-dependencies", "dependency-graph", "graphviz"]
categories = ["config", "data-structures", "development-tools", "parser-implementations"]
edition = "2018"
exclude = [
    # Skip over test fixtures since they're pretty large (several MB).
    "fixtures/*",
    # Readme template that doesn't need to be included.
    "README.tpl",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
circle-ci = { repository = "calibra/cargo-guppy", branch = "master"}
maintenance = { status = "actively-developed" }

[dependencies]
cargo_metadata = "0.9"
derivative = "1.0.3"
fixedbitset = { version = "0.1.4", default-features = false }
lazy_static = "1.4.0"
petgraph = "0.4.13"
semver = "0.9.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
toml = "0.5.3"
