[package]
name = "guppy"
version = "0.5.0"
description = "Track and query Cargo dependency graphs."
documentation = "https://docs.rs/guppy"
repository = "https://github.com/facebookincubator/cargo-guppy"
authors = ["Rain <rain1@calibra.com>", "Brandon Williams <bmwill@calibra.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["cargo", "dependencies", "reverse-dependencies", "dependency-graph", "graphviz"]
categories = ["config", "data-structures", "development-tools", "parser-implementations"]
edition = "2018"
exclude = [
    # Readme template that doesn't need to be included.
    "README.tpl",
]

[package.metadata.docs.rs]
all-features = true

[badges]
circle-ci = { repository = "facebookincubator/cargo-guppy", branch = "master"}
maintenance = { status = "actively-developed" }

[dependencies]
cargo_metadata = "0.10.0"
guppy-summaries = { version = "0.2.0", path = "../guppy-summaries", optional = true }
fixedbitset = { version = "0.3.0", default-features = false }
nested = "0.1.1"
indexmap = "1.5.1"
itertools = "0.9.0"
once_cell = "1.4.1"
pathdiff = "0.2.0"
petgraph = { version = "0.5.1", default-features = false }
proptest = { version = "0.10.1", optional = true }
proptest-derive = { version = "0.2.0", optional = true }
semver = "0.9.0"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
supercow = "0.1.0"
target-spec = { version = "0.4.0", path = "../target-spec" }

[dev-dependencies]
assert_matches = "1.3.0"
fixtures = { path = "../fixtures" }
pretty_assertions = "0.6.1"

[features]
proptest010 = ["proptest", "proptest-derive", "target-spec/proptest010"]
# summaries is NOT currently part of the stable API.
summaries = ["guppy-summaries", "target-spec/summaries"]
