on:
  push:
    branches:
      - main

name: Docs

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build rustdoc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features
      - name: Build presentations
        uses: KoharaKazuya/marp-cli-action@v1
        with:
          # TODO: figure out how to turn this into a script to run on all presentations in the repo
          config-file: presentations/2021-02/.marprc
      - name: Organize
        run: |
          mkdir target/gh-pages
          mv target/doc target/gh-pages/rustdoc
          cp -R presentations target/gh-pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/gh-pages
